name: test_workflow_2

on: push

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.11.5]

    name: UnitaryTests
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pytest
          pip install requests
          pip install pandas
          pip install numpy
          pip install imbalanced-learn
          pip install lightgbm
      - name: Run tests
        run: pytest
